<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Qwaitumin.LibreAutoTile.GodotBindings</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LibreAutoTile\Qwaitumin.LibreAutoTile.csproj" />
    <PackageReference Include="GodotSharp" Version="$(GodotSharpVersion)" />
  </ItemGroup>

  <ItemGroup>
    <None Include="LICENSE" Pack="true" PackagePath="" />
    <None Include="README.md" Pack="true" PackagePath="" />
  </ItemGroup>

  <PropertyGroup>
    <PackageId>Qwaitumin.LibreAutoTile.GodotBindings</PackageId>
    <Authors>ruedoux</Authors>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <Description>Autotile algorithm implementation bindings for godot</Description>
    <RepositoryUrl>https://github.com/ruedoux/libre-auto-tile</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/ruedoux/libre-auto-tile</PackageProjectUrl>
    <PackageTags>auto tile libreautotile autotile libre godot bindings</PackageTags>

    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="all" />
  </ItemGroup>

</Project>
