<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Qwaitumin.LibreAutoTile.GodotBindings</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LibreAutoTile\Qwaitumin.LibreAutoTile.csproj" />
    <PackageReference Include="GodotSharp" Version="$(GodotSharpVersion)" />
  </ItemGroup>

  <ItemGroup>
    <None Include="LICENSE" Pack="true" PackagePath="" />
    <None Include="README.md" Pack="true" PackagePath="" />
  </ItemGroup>

  <PropertyGroup>
    <PackageId>Qwaitumin.LibreAutoTile.GodotBindings</PackageId>
    <Authors>ruedoux</Authors>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <Description>Autotile algorithm implementation bindings for godot</Description>
    <RepositoryUrl>https://github.com/ruedoux/libre-auto-tile/tree/main</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>auto tile libreautotile autotile libre godot bindings</PackageTags>
  </PropertyGroup>

</Project>
