<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\LibreAutoTile\Qwaitumin.LibreAutoTile.csproj" />
    <ProjectReference Include="..\modules\simple-test\SimpleTest\Qwaitumin.SimpleTest.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Qwaitumin.LibreAutoTile.Tests</RootNamespace>
  </PropertyGroup>

</Project>
