<Project Sdk="Godot.NET.Sdk/4.5.1">
  <PropertyGroup>
    <RootNamespace>Qwaitumin.LibreAutoTile.GodotBingings.Tests</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LibreAutoTile.GodotBindings\Qwaitumin.LibreAutoTile.GodotBindings.csproj" />
    <ProjectReference Include="..\modules\simple-test\SimpleTest\Qwaitumin.SimpleTest.csproj" />
  </ItemGroup>
</Project>